[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Aditya-Kumar-Code", email = "87271653+Aditya-Kumar-Code@users.noreply.github.com" }
]
requires-python = ">=3.11"
dependencies = [
    "faiss-cpu>=1.15.1",
    "fastapi>=0.141.1",
    "langchain>=1.4.2",
    "langchain-community>=0.4.2",
    "langchain-google-genai>=4.0.0",
    "langgraph>=1.2.12",
    "pypdf>=6.19.0",
    "python-dotenv>=1.2.3",
    "uvicorn>=0.54.0",
]

[project.scripts]
backend = "backend:main"

[tool.uv]
package = false

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]

[tool.pytest.ini_options]
pythonpath = ["."]
